In [37]:
import gdown
import pandas as pd

gdown.download(r'https://bit.ly/3RhoNho', 'ns_202104.csv', quiet=False)
ns_df = pd.read_csv('ns_202104.csv', low_memory=False)
ns_df.head()

Downloading...
From: https://bit.ly/3RhoNho
To: c:\data\ns_202104.csv
100%|██████████| 57.6M/57.6M [00:05<00:00, 9.78MB/s]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [69]:
count_df = ns_df[['도서명', '저자', 'ISBN', '권', '대출건수']]
loan_df = count_df.groupby(by=['도서명', '저자', 'ISBN', '권'], dropna=False).sum()

#원본 데이터프레임 중복된 행 삭제하기 
ns_df2 = ns_df.drop_duplicates(subset=['도서명', '저자', 'ISBN', '권']).copy()
ns_df2.duplicated(subset=['도서명', '저자', 'ISBN', '권']).sum()

#원본 데이터프레임의 선택 열들을 인덱스로 만들기(update의 겹침 기준은 칼럼 키가 아닌 인덱스 번호/라벨이기 때문!)
ns_df2.set_index(['도서명', '저자', 'ISBN', '권'], inplace=True)
ns_df2

#원본 데이터프레임과 병합하기
ns_df2.update(loan_df)
ns_df2.reset_index(inplace=True)
ns_df2 = ns_df2[ns_df.columns]

In [78]:
#일괄 처리 함수 만들기(필요 없는 행 및 열을 삭제 -> 중복된 행을 대출건수 기준으로 병합하는 함수)
import pandas as pd
import numpy as np

#함수 정의
def data_cleaning(csv_file):
    
    #파일을 데이터프레임으로 읽기
    dfO = pd.read_csv(csv_file, low_memory=False, encoding='utf-8-sig')
    df = dfO.copy()
    
    #결측치 제거
    df.replace(r'^\s*$', np.nan, regex=True, inplace=True)
    df.dropna(axis=1, how='all', inplace=True)
    df.dropna(how='all', inplace=True)
    
    #대출건수를 도서명, 저자, ISBN, 권수 기준으로 병합하여 새로운 데이터 프레임 만들기
    count_df = df[['도서명', '저자', 'ISBN', '권', '대출건수']]
    loan_count_df = count_df.groupby(by=['도서명', '저자', 'ISBN', '권'], dropna=False).sum()
    
    #기존 데이터프레임과 합치기
    df.drop_duplicates(subset=['도서명', '저자', 'ISBN', '권'], inplace=True)
    df.set_index(['도서명', '저자', 'ISBN', '권'], inplace=True)
    
    df.update(loan_count_df)
    df = df.reset_index()
    
    
    return df

gdown.download(r'https://bit.ly/3RhoNho', 'ns_202104.csv', quiet=False)

Downloading...
From: https://bit.ly/3RhoNho
To: c:\data\ns_202104.csv
100%|██████████| 57.6M/57.6M [00:05<00:00, 9.63MB/s]

'ns_202104.csv'

In [80]:

ns_new_book = data_cleaning('ns_202104.csv')
ns_new_book

,도서명,저자,ISBN,권,번호,출판사,발행년도,세트 ISBN,부가기호,주제분류번호,도서권수,대출건수,등록일자
0,인공지능과 흙,김동훈 지음,9788937444319,NaN,1,민음사,2021,NaN,NaN,NaN,1,0,2021-03-19
1,가짜 행복 권하는 사회,김태형 지음,9791190123969,NaN,2,갈매나무,2021,NaN,NaN,NaN,1,0,2021-03-19
2,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,9788968332982,NaN,3,블랙피쉬,2021,NaN,NaN,NaN,1,0,2021-03-19
3,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",9788970759906,NaN,4,문학세계사,2021,NaN,NaN,NaN,1,0,2021-03-19
4,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,9788934990833,NaN,5,김영사,2021,NaN,NaN,NaN,1,0,2021-03-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
384586,소설의 사회사 비교론,조동일 지음,9788942340262,3,401674,지식산업사,2001,9788942300365,NaN,809.3,1,0,1970-01-01
384587,큰오빠,박정근 지음,9788974231323,2,401677,우리문학사,1998,9788974231309,NaN,813.6,2,0,1970-01-01
384588,韓國現代詩大系,채만묵 編著,9788977352971,3,401678,한국문화사,1996,9788977352988,NaN,811.608,1,0,1970-01-01
384589,뉴 웨이브,제임스 모나코 지음,9788985367448,2,401679,한나래,1996,9788985367424,NaN,688.04,1,0,1970-01-01
384590,독일 문학과 세계 문학,吳漢鎭 編著,9788947700368,3,401681,벽호,1995,9788947700405,NaN,809.05,2,0,1970-01-01