In [ ]:
import pandas as pd
import gdown

ns_book6 = pd.read_csv(r'C:\data\ns_book6.csv', low_memory=False)
ns_book6.head(6)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021.0,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021.0,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021.0,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021.0,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021.0,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19
5,6,처음 읽는 음식의 세계사,"미야자키 마사카츠 지음, 한세희 옮김",탐나는책,2021.0,9791189550370,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [3]:
ns_book6.describe(include='object')
ns_book6.describe()

ns_book7 = ns_book6[ns_book6['도서권수']>0]

In [17]:
#기술통계 판다스 메서드
import re
import numpy as np
ns_book7.describe()
ns_book8 = ns_book7.copy()

s = ns_book8['주제분류번호'].astype('string').str.strip()
f = ~ s.str.contains(r'\d', regex=True, na=True)

def cleansing(x):
    global s
    if x == '<NA>':
        x = np.nan
    if pd.isna(x):
        return '-1'
    if str(x).strip() == '':
        return '-1'
    else:   
        return str(x).strip()[0]
    
주제분류번호 = ns_book8['주제분류번호'].apply(cleansing)
ns_book8['주제분류번호'] = 주제분류번호

ns_book8['주제분류번호'].mode()

0    8
Name: 주제분류번호, dtype: object

In [14]:
import numpy as np

np.average(ns_book7['대출건수'])
np.average(ns_book7['대출건수'], weights=1/ns_book7['도서권수'])

ns_book7['등록일자'] = pd.to_datetime(ns_book7['등록일자'], format='%Y-%m-%d', errors='coerce')
기준연월 = pd.Timestamp('2022-12-31')
경과일수 = (기준연월 - ns_book7['등록일자']).dt.days
ns_book7['경과일수'] = 경과일수

np.average(ns_book7['대출건수'], weights=1/ns_book7['경과일수'])

# ns_book['등록일자_dt'] = pd.to_datetime(ns_book['등록일자'], format='%Y-%m-%d', errors='coerce')
# 기준연월 = pd.Timestamp('2022-12-31')
# 가용일수 = (기준연월 - ns_book['등록일자_dt']).dt.days

C:\Users\박중현\AppData\Local\Temp\ipykernel_7380\1782863072.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ns_book7['등록일자'] = pd.to_datetime(ns_book7['등록일자'], format='%Y-%m-%d', errors='coerce')
C:\Users\박중현\AppData\Local\Temp\ipykernel_7380\1782863072.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ns_book7['경과일수'] = 경과일수

np.float64(9.404718905148764)

In [ ]:
idx, val = np.unique(ns_book8['주제분류번호'], return_counts=True)

max_val = np.argmax(val)
idx[max_val]

'8'

In [36]:
import gdown
import matplotlib.pyplot as plt

gdown.download(r'https://bit.ly/3pK7iuu', 'ns_book7.csv', quiet = False)
ns_book7 = pd.read_csv('ns_book7.csv', low_memory=False)
ns_book7.head()

Downloading...
From: https://bit.ly/3pK7iuu
To: c:\data\ns_book7.csv
100%|██████████| 53.8M/53.8M [00:04<00:00, 10.8MB/s]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [ ]:
plt.scatter(range(1, 10), range(1, 20, 2))