In [1]:
import gdown
import pandas as pd

gdown.download(r'https://bit.ly/3GisL6J', 'ns_book4.csv', quiet=False)

ns_book4 = pd.read_csv('ns_book4.csv', low_memory=False)
ns_book4.head()

Downloading...
From: https://bit.ly/3GisL6J
To: c:\data\ns_book4.csv
100%|██████████| 55.5M/55.5M [00:05<00:00, 10.6MB/s]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0.0,2021-03-19

In [2]:
import numpy as np
ns_book4.loc[0, '도서권수'] = 1
ns_book4 = ns_book4.astype({'도서권수':'int64', '대출건수':'int64'})

ns_book4.loc[0, '부가기호'] = np.nan
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [3]:
ns_book4.loc[ns_book4['부가기호'].isna(), '부가기호'] = '없음'
ns_book4.fillna({'부가기호':'없음'}).isna().sum()

번호              0
도서명           403
저자            198
출판사          4641
발행년도           14
ISBN            0
세트 ISBN    328015
부가기호            0
권          321213
주제분류번호      19864
도서권수            0
대출건수            0
등록일자            0
dtype: int64

In [4]:
# DataFrame의 <replace>와 <정규식>
# ns_book4.replace({'발행년도':{r'\d\d(\d\d)':r'\1'}}, regex=True)[100:102]

ns_book4.replace({'발행년도':{r"\d\d(\d\d)":r"\1"}, '저자':{r"(.*)\s\(지은이\)(.*)\s\(옮긴이\)":r"\1\2"}}, regex=True)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,21,9788937444319,NaN,없음,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,21,9791190123969,NaN,없음,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,21,9788968332982,NaN,없음,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,21,9788970759906,NaN,없음,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,21,9788934990833,NaN,없음,NaN,NaN,1,0,2021-03-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
384586,401674,소설의 사회사 비교론,조동일 지음,지식산업사,01,9788942340262,9788942300365,없음,3,809.3,1,0,1970-01-01
384587,401677,큰오빠,박정근 지음,우리문학사,98,9788974231323,9788974231309,없음,2,813.6,2,0,1970-01-01
384588,401678,韓國現代詩大系,채만묵 編著,한국문화사,96,9788977352971,9788977352988,없음,3,811.608,1,0,1970-01-01
384589,401679,뉴 웨이브,제임스 모나코 지음,한나래,96,9788985367448,9788985367424,없음,2,688.04,1,0,1970-01-01
384590,401681,독일 문학과 세계 문학,吳漢鎭 編著,벽호,95,9788947700368,9788947700405,없음,3,809.05,2,0,1970-01-01

In [5]:
invalid_number = ns_book4['발행년도'].str.contains('\D', na=True)
ns_book4[invalid_number]

ns_book5 = ns_book4.replace({'발행년도': {r'.*(\d{4}).*':r'\1'}}, regex=True)
invalid_number = ns_book5['발행년도'].str.contains('\D', na=True)
#print(invalid_number.sum()) 67개 
ns_book5[invalid_number]

ns_book5.loc[invalid_number, '발행년도'] = '-1'
ns_book5 = ns_book5.astype({'발행년도':'int64'})


#-----------------------이상값 교체하기----------------------------#
dk_year_row = ns_book5['발행년도'].gt(4000)
ns_book5.loc[dk_year_row, '발행년도'] = ns_book5.loc[dk_year_row, '발행년도'] - 2333

ns_book5['발행년도'].gt(4000).sum()
ns_book5.loc[dk_year_row, '발행년도'] = -1

old_books = ns_book5['발행년도'].gt(0) & ns_book5['발행년도'].lt(1900)
ns_book5.loc[old_books, '발행년도'] = -1

rows_minus = ns_book5['발행년도'].eq(-1)
rows_minus.sum()

np.int64(204)

In [6]:
na_rows = ns_book5['저자'].isna() | ns_book5['출판사'].isna() \
    | ns_book5['도서명'].isna() | ns_book5['발행년도'].eq(-1)

ns_book5[na_rows]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
78,79,아산 정주영 레거시,김화진,NaN,2021,9788952129529,NaN,없음,NaN,325,1,1,2021-03-15
265,278,골목의 시간을 그리다,정명섭.김효찬 지음,NaN,2021,9791191266054,NaN,없음,NaN,NaN,1,0,2021-03-12
354,367,한국인의 맛,정명섭 지음,NaN,2021,9791155401804,NaN,없음,NaN,NaN,1,0,2021-03-12
539,552,"한성부, 달 밝은 밤에",김이삭 지음,NaN,2021,9791163161479,NaN,없음,NaN,NaN,1,0,2021-03-12
607,620,100일 완성 마그마 러시아어 중고급 단어장,러포자 구제 연구소 외 지음,NaN,2021,9788974829193,NaN,없음,NaN,NaN,1,0,2021-03-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
383830,400875,경기 동부지역,한국지역개발연구원 編,NaN,2000,9780200011501,NaN,없음,NaN,539.702,1,0,1970-01-01
384046,401116,(회화완성)新中國語,北京語言學院 저,NaN,1994,9788982440298,NaN,없음,NaN,727,1,0,1970-01-01
384097,401172,都市經營,李圭憲 編著,NaN,1995,9788987569468,NaN,없음,NaN,359.008,1,0,1970-01-01
384325,401407,미스코리아 살인사건,이승영 저,NaN,1991,9788985351355,NaN,없음,NaN,813.6,1,0,1970-01-01
384476,401558,영원한 만남의 기도,김영채 엮음,NaN,1988,9788900017014,NaN,없음,NaN,237.2,1,0,1970-01-01

In [ ]:
import re
import requests
import pandas
from bs4 import BeautifulSoup

def find_bookinfo(row):
    title = row['도서명']
    author = row['저자']
    pub = row['출판사']
    year = row['발행년도']
    
    #URL로 페이지 html 텍스트 가져오기
    url = r"https://www.yes24.com/product/search?domain=ALL&query={}"
    headers={"User-Agent":"Mozilla/5.0"}
    try:
        page_html = requests.get(url.format(row['ISBN']), headers=headers, timeout=3)
        page_html.raise_for_status()
    except requests.RequestException as err:
        return f"{row['ISBN']}: {err}"
    page_soup = BeautifulSoup(page_html.text, 'html.parser')
    
    #전체 태그 박스 찾기
    box_li = page_soup.select_one("li[data-goods-no][data-iy-no][data-statgb]")
    if box_li is None:
        return title, author, pub, year
    
    #제목 태그 찾기
    if pd.isna(title):
        title_gd = box_li.select_one("a.gd_name")
        title = title_gd.get_text('', strip=True) if title_gd else None
        
    #저자 태그 찾기
    if pd.isna(author):
        author_span = box_li.select_one("span.info_auth")
        author_list = author_span.select("a") if author_span else []
        author = ', '.join(a.get_text(strip=True) for a in author_list) if author_list else author
    
        
    #출판사 태그 찾기
    if pd.isna(pub):
        pub_span = box_li.select_one("span.authPub.info_pub")
        pub = pub_span.get_text(" ", strip=True) if pub_span else None
    
    #발행년도 태그 찾기
    if pd.isna(year):
        year_span = box_li.select_one("span.authPub.info_date")
        year_str = year_span.get_text(strip=True) if year_span else None
        year = re.findall(r'\d{4}', year_str)[0]
    
    return title, author, pub, year

KeyboardInterrupt:

In [ ]:
sample = ns_book5[na_rows].head(20).apply(find_bookinfo, axis=1, result_type='expand')
cols = ['도서명', '저자', '출판사', '발행년도']
sample.columns = cols

,도서명,저자,출판사,발행년도
78,아산 정주영 레거시,김화진,서울대학교출판문화원,2021
265,골목의 시간을 그리다,정명섭.김효찬 지음,초록비책공방,2021
354,한국인의 맛,정명섭 지음,추수밭,2021
539,"한성부, 달 밝은 밤에",김이삭 지음,고즈넉이엔티,2021
607,100일 완성 마그마 러시아어 중고급 단어장,러포자 구제 연구소 외 지음,문예림,2021
646,수채 과슈로 그리는 나의 반려식물,송현미 지음,북핀,2021
991,더 믹솔로지,"나구모 슈조 지음, 김수연 옮김, 성중용 감수",한스미디어,2021
1164,(101개 실습 동영상 보면서 배우는)영상편집 with 프리미어 프로 :1페이지 핵...,"신의현,서준성 공저",앤써북,2021
1165,(맛있는 디자인) 포토샵 & 일러스트레이터 CC 2021 :누구나 쉽게 배워 제대로...,"빨간고래,윤이사라 지음",한빛미디어,2021
1177,내 아이의 부자 수업 :상위 1퍼센트 유대인의 하브루타 경제 독립 교육,김금선 지음,한국경제신문사(한경비피),2021
1312,귀를 씻다,이선식 지음,문학수첩,2020
1784,"바쁘다, 바빠! 소방관 24시(움아1)","엠마뉴엘 케시르-르프티 지음, 프랑수아 다니엘 외 그림, 김현희 옮김",푸른숲주니어,2020
2476,널 만나러 지구로 갈게,김성일 지음,돌베개,2020
3612,대한민국 국가지도집,국토교통부 국토지리정보원 [편],NaN,2019
3613,문재인 대통령 연설문집,대통령비서실 [편],NaN,2020
3614,문재인 대통령 연설문집,대통령비서실 [편],NaN,2020
3615,한국직업사전:통합본 제5판,한국고용정보원 [편],NaN,2019
3642,대한민국 국가지도집 Ⅰ 2019,NaN,NaN,2019
3646,광복 이후 서울 학생들의 통학과 생활문화,박명호,서울책방,2020
3651,"『삼국사기』초기 기록, 어디까지 믿을 수 있나",김기섭,서울책방,2020

In [ ]:
gdown.download(r'https://bit.ly/3UJZiHw', 'ns_book5_update.csv', quiet=False)
ns_book5_update = pd.read_csv('ns_book5_update.csv', low_memory=False, index_col=0) #인덱스 칼럼의 열은 열의 0번째로 쓰겠다
ns_book5_update

Downloading...
From: https://bit.ly/3UJZiHw
To: c:\data\ns_book5_update.csv
100%|██████████| 406k/406k [00:00<00:00, 2.81MB/s]

                             도서명               저자         출판사  발행년도
78                    아산 정주영 레거시              김화진  서울대학교출판문화원  2021
265                  골목의 시간을 그리다       정명섭.김효찬 지음      초록비책공방  2021
354                       한국인의 맛           정명섭 지음         추수밭  2021
539                 한성부, 달 밝은 밤에           김이삭 지음      고즈넉이엔티  2021
607     100일 완성 마그마 러시아어 중고급 단어장  러포자 구제 연구소 외 지음         문예림  2021
...                          ...              ...         ...   ...
383830                   경기 동부지역      한국지역개발연구원 編         NaN  2000
384046                (회화완성)新中國語         北京語言學院 저         NaN  1994
384097                      都市經營           李圭憲 編著         NaN  1995
384325                미스코리아 살인사건            이승영 저         NaN  1991
384476                영원한 만남의 기도           김영채 엮음         NaN  1988

[5268 rows x 4 columns]

In [ ]:
ns_book5.update(ns_book5_update)

na_rows = ns_book5['저자'].isna() | ns_book5['출판사'].isna() \
    | ns_book5['도서명'].isna() | ns_book5['발행년도'].eq(-1)
    
ns_book6 = ns_book5.dropna(subset=['저자', '출판사', '도서명'])
ns_book6 = ns_book6[ns_book6['발행년도'] != -1]
ns_book6.to_csv('ns_book6.csv', encoding='utf-8', index=False)

In [ ]:
ns_book4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384591 entries, 0 to 384590
Data columns (total 13 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   번호       384591 non-null  int64
 1   도서명      384188 non-null  object
 2   저자       384393 non-null  object
 3   출판사      379950 non-null  object
 4   발행년도     384577 non-null  object
 5   ISBN     384591 non-null  object
 6   세트 ISBN  56576 non-null   object
 7   부가기호     384591 non-null  object
 8   권        63378 non-null   object
 9   주제분류번호   364727 non-null  object
 10  도서권수     384591 non-null  int64
 11  대출건수     384591 non-null  int64
 12  등록일자     384591 non-null  object
dtypes: int64(3), object(10)
memory usage: 38.1+ MB